### ISSUE TITLE
[Feature Request] Upgrades in result pipe

### ISSUE THREAD

**Issue by Thorsten6697** [tom5454/LogisticsBridge#46] opened 2020-08-25 23:46 UTC
Could you add the possibility to add Action Speed and/or Stack upgrades to the result pipe, because in some cases it's to slow.

**Comment by tom5454** [comment] 2020-08-26 08:57
Duplicate of #38

**Comment by tom5454** [comment] 2020-08-26 08:58
You can install an Advanced Extraction Upgrade into Result Pipes.

**Closed by tom5454** 2020-08-26 08:57 UTC
