### ISSUE TITLE
AE Bridge miscalculation

### ISSUE THREAD

**Issue by nico1207** [tom5454/LogisticsBridge#30] opened 2020-07-31 11:58 UTC
Something about autocrafting using an AE system and crafting manager pipes is wrong.

I have the following setup:

1 Alloy Smelter with this recipe:
- 1 Copper Ingot + 4 Redstone = 1 Red Alloy Ingot

1 Wiremill with these recipes:
- 1 Red Alloy Ingot = 2 Red Alloy Wire
- 1 Red Alloy Wire = 4 Fine Red Alloy Wire

If I use a Logistics Request Table to request 8 Fine Red Alloy Wire the system correctly crafts 1 Red Alloy Ingot, 2 Wires and finally 8 Fine Red Alloy Wires.
If I use an ME Terminal that is connected to the logistics system and request 8 Fine Red Alloy Wire, it crafts 2 Red Alloy Ingots, turns them into 4 Wires and finally turns 2 of these Wires into 8 Fine Red Alloy Wire. It shouldn't do that, since it works fine in the Logistics Request Table.

**Comment by tom5454** [comment] 2020-08-01 12:04
Duplicate of #16 
The issue is with AE, from AE's view a recipe exists with 1 Copper Ingot + 4 Redstone = 4 Fine Red Alloy Wire + 1 Red Alloy Wire
because this is the result of requesting 1 Fine Red Alloy Wire.
Logistics Bridge doesn't have access to the amount AE wants to craft, it asks for 1 set and multipiles the ingredients.

**Closed by tom5454** 2020-08-01 12:04 UTC

**Comment by nico1207** [comment] 2020-08-01 17:43
I just made my own build of the mod and fixed it.

**Comment by ghost** [comment] 2020-09-17 17:25
With _"I just made my own build of the mod and fixed it."_ do you mean that you forked the source and fixed the problem? If you did, can you create a PR?

**Comment by nico1207** [comment] 2020-09-17 17:28
I forked the source and fixed it, but it's a rather hacky solution and should therefore only be used as inspiration to create an official fix.

**Comment by ghost** [comment] 2020-09-17 17:37
Is [this fork](https://github.com/nico1207/LogisticsBridge) already up-to-date with that patch?

**Comment by nico1207** [comment] 2020-09-17 17:45
It's using an older patch, 1.3.9 I think

**Comment by nico1207** [comment] 2020-09-17 18:09
yes

**Comment by ghost** [comment] 2020-09-17 18:10
Could you please post the jar file somewhere?

**Comment by nico1207** [comment] 2020-09-17 18:36
https://mega.nz/file/G88lULST#YEeYDIVt33lrkJZtq-g7Ac-0-jk1mPEryd47l7WiEdY

**Comment by ghost** [comment] 2020-09-17 21:46
Are you sure this is working? Because it literally broke everything. The applied can't see some items as craftable and when it works, it says there are not enough items in the storage

**Comment by nico1207** [comment] 2020-09-17 21:48
I've been using it for most of my FTB:Interactions playthrough, haven't had any problems.. :/

**Comment by ghost** [comment] 2020-09-17 21:49
https://imgur.com/a/3GtusMq

**Comment by nico1207** [comment] 2020-09-17 21:50
That's really strange. Is the cobblestone stored in your ME system or in the Logistics Pipes part?

**Comment by ghost** [comment] 2020-09-17 21:50
I use the ME System for the storage

**Comment by ghost** [comment] 2020-09-17 21:51
And it doesn't see the craftings from the crafting logistics pipes

**Comment by nico1207** [comment] 2020-09-17 21:52
> And it doesn't see the craftings from the crafting logistics pipes

I can see why that might be the case. As I said it is quite hacky and tailored to my specific needs, so I only ever tested it with Logistics Bridge's Crafting Manager pipes.

**Comment by nico1207** [comment] 2020-09-17 21:55
Maybe we should continue to chat on discord? Add "Nico Tin#8105" if you want to keep debugging this
